# -*- coding: utf-8 -*-
"""1_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcuFnoTy9zG9ehHsm4v8LWh0uEuC08Ic
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -r /content/drive/MyDrive/req.txt

# -*- coding: utf-8 -*-
"""
1_analysis.py  —  Identify RT targets, detect PTV cropping, export crop_analysis.xlsx.

Pipeline:
  1. Scan dati_estratti/ to build uid_to_files  {uid → {RS, RP, RD}}
  2. Read prescription from RP; identify target ROIs via DVH or voxel dose
  3. Match ITV/CTV ↔ PTV; resolve mismatches automatically or via manual input
  4. For each pair compute expected margin and flag cropped PTVs
  5. Save  crop_analysis_new.xlsx  and  uid_to_files_new.xlsx
"""

# ── Standard imports ──────────────────────────────────────────────────────────
import os
import re
import zipfile
import shutil

import numpy as np
import pandas as pd
import pydicom
from glob import glob
from scipy import stats
from shapely.geometry import Point, Polygon

# ── Configuration ─────────────────────────────────────────────────────────────
MAINFOLDER   = '/content/drive/MyDrive/ColabNotebooks/crop/'
DATASET_PATH = os.path.join(MAINFOLDER, 'dataset_grande', 'dati_estratti')
CROP_THRESHOLD = 0.10   # fraction of PTV points that must be cropped to flag


# ══════════════════════════════════════════════════════════════════════════════
# Helper utilities
# ══════════════════════════════════════════════════════════════════════════════

def trova_file_con_prefisso(cartella_base: str, prefisso: str) -> list[str]:
    """Recursively find all files whose name starts with *prefisso*."""
    return [
        os.path.join(root, f)
        for root, _, files in os.walk(cartella_base)
        for f in files
        if f.startswith(prefisso)
    ]


def ottieni_file_da_uid(uid_to_files: dict, study_uid: str, file_type: str) -> str:
    """Return the path for *file_type* ('RS', 'RP', or 'RD') of *study_uid*."""
    if study_uid not in uid_to_files:
        raise ValueError(f"StudyInstanceUID '{study_uid}' not found.")
    if file_type not in {"RS", "RP", "RD"}:
        raise ValueError(f"File type '{file_type}' invalid. Use 'RS', 'RP', or 'RD'.")
    path = uid_to_files[study_uid].get(file_type)
    if not path:
        raise ValueError(f"No '{file_type}' file for '{study_uid}'.")
    return path


def riordina_liste(lista1: list, lista2: list) -> tuple[list, list]:
    """
    Interactively reorder two parallel lists.
    The user assigns a new position index to each element of lista1;
    lista2 is reordered identically.
    """
    print("Lista 1:", lista1)
    print("Lista 2:", lista2)
    nuovi_indici = []
    for i, elem in enumerate(lista1):
        while True:
            try:
                idx = int(input(
                    f"New position for '{elem}' (0–{len(lista1)-1}): "
                ))
                if 0 <= idx < len(lista1) and idx not in nuovi_indici:
                    nuovi_indici.append(idx)
                    break
                print("Invalid or already-used index — try again.")
            except ValueError:
                print("Please enter an integer.")
    lista1_ord = [lista1[i] for i in nuovi_indici]
    lista2_ord = [lista2[i] for i in nuovi_indici]
    print("Reordered Lista 1:", lista1_ord)
    print("Reordered Lista 2:", lista2_ord)
    return lista1_ord, lista2_ord


# ══════════════════════════════════════════════════════════════════════════════
# Geometry / structure analysis
# ══════════════════════════════════════════════════════════════════════════════

def process_struct(S1: np.ndarray, S2: np.ndarray) -> tuple[float, list, float]:
    """
    Compute the expected CTV→PTV expansion and detect cropped PTV points.

    Parameters
    ----------
    S1 : (N,3) array — CTV contour points (x, y, z) in mm
    S2 : (N,3) array — PTV contour points

    Returns
    -------
    expected_expansion : float   — modal positive distance S2→S1 boundary
    cropped_points     : list    — distances below 80 % of expected expansion
    max_crop           : float   — largest missing margin in mm
    """
    z_values = np.unique(np.concatenate((S1[:, 2], S2[:, 2])))
    dist = []

    for z in z_values:
        slice_S1 = S1[np.isclose(S1[:, 2], z)]
        slice_S2 = S2[np.isclose(S2[:, 2], z)]

        if len(slice_S1) < 3:
            continue

        poly = Polygon(slice_S1[:, :2])
        if not poly.is_valid:
            poly = poly.buffer(0)   # attempt auto-repair

        for pt in slice_S2:
            point2D = Point(pt[0], pt[1])
            d = point2D.distance(poly.exterior)
            if poly.contains(point2D):
                d = -d
            dist.append(d)

    if not dist:
        return 0.0, [], 0.0

    positive_dists = [d for d in dist if d > 0]
    if not positive_dists:
        return 0.0, [], 0.0

    expected_expansion = float(stats.mode(positive_dists, axis=None)[0])
    print(f"  Expected expansion: {round(expected_expansion)} mm")

    cropped_points = [d for d in dist if d < expected_expansion * 0.8]
    max_crop = (expected_expansion - min(cropped_points)) if cropped_points else 0.0

    return expected_expansion, cropped_points, max_crop


def extract_contour_points(contour_seq, roi_number: int) -> list:
    """Pull flat ContourData list for a given ROI number from ROIContourSequence."""
    points = []
    for m in contour_seq:
        if m.ReferencedROINumber == roi_number:
            for cs in m.ContourSequence:
                points.extend(cs.ContourData)
    return points


# ══════════════════════════════════════════════════════════════════════════════
# Dose-based target identification
# ══════════════════════════════════════════════════════════════════════════════

def calcola_target_da_dose(uid_to_files: dict, studyUID: str, prs: float) -> list:
    """
    Identify target ROIs by comparing mean voxel dose to 50% of prescription.
    Falls back to name-matching (PTV / CTV) if no ROI meets the dose threshold.
    """
    rs = pydicom.dcmread(ottieni_file_da_uid(uid_to_files, studyUID, 'RS'))
    rd = pydicom.dcmread(ottieni_file_da_uid(uid_to_files, studyUID, 'RD'))

    dose_grid = rd.pixel_array * rd.DoseGridScaling
    dose_shape = dose_grid.shape
    ipp = np.array(rd.ImagePositionPatient, dtype=float)
    spacing = np.array([
        float(rd.PixelSpacing[0]),
        float(rd.PixelSpacing[1]),
        float(rd.GridFrameOffsetVector[1] - rd.GridFrameOffsetVector[0]),
    ])

    roi_names = {roi.ROINumber: roi.ROIName.upper() for roi in rs.StructureSetROISequence}
    targets = []

    for roi_contour in rs.ROIContourSequence:
        if not hasattr(roi_contour, 'ContourSequence'):
            continue
        voxels = []
        for contour in roi_contour.ContourSequence:
            coords = np.array(contour.ContourData).reshape(-1, 3)
            indices = np.round((coords - ipp) / spacing).astype(int)
            for idx in indices:
                z, y, x = idx[::-1]
                if 0 <= z < dose_shape[0] and 0 <= y < dose_shape[1] and 0 <= x < dose_shape[2]:
                    voxels.append(dose_grid[z, y, x])
        if voxels and np.mean(voxels) >= 0.5 * prs:
            targets.append(roi_contour.ReferencedROINumber)

    if not targets:
        print("  Fallback: matching by structure name (PTV/CTV)")
        targets = [
            num for num, name in roi_names.items()
            if re.search(r'\b(PTV|CTV)\b', name)
        ]

    return targets


def get_mean_dose_per_roi(uid_to_files: dict, studyUID: str,
                          roi_numbers: list | None = None) -> dict:
    """
    Return {roi_number_str: mean_dose}.
    Uses DVHSequence when available, otherwise falls back to voxel sampling.
    """
    rd = pydicom.dcmread(ottieni_file_da_uid(uid_to_files, studyUID, 'RD'))

    # Fast path: DVHSequence
    if hasattr(rd, 'DVHSequence'):
        return {
            str(dvh.DVHReferencedROISequence[0].ReferencedROINumber): float(dvh.DVHMeanDose)
            for dvh in rd.DVHSequence
            if roi_numbers is None
               or str(dvh.DVHReferencedROISequence[0].ReferencedROINumber) in roi_numbers
        }

    # Voxel-based fallback
    rs = pydicom.dcmread(ottieni_file_da_uid(uid_to_files, studyUID, 'RS'))
    dose_grid = rd.pixel_array * rd.DoseGridScaling
    dose_shape = dose_grid.shape
    ipp = np.array(rd.ImagePositionPatient, dtype=float)
    spacing = np.array([
        float(rd.PixelSpacing[0]),
        float(rd.PixelSpacing[1]),
        float(rd.GridFrameOffsetVector[1] - rd.GridFrameOffsetVector[0]),
    ])

    mean_doses = {}
    for roi_contour in rs.ROIContourSequence:
        roi_num = str(roi_contour.ReferencedROINumber)
        if roi_numbers is not None and roi_num not in roi_numbers:
            continue
        if not hasattr(roi_contour, 'ContourSequence'):
            continue
        voxels = []
        for contour in roi_contour.ContourSequence:
            coords = np.array(contour.ContourData).reshape(-1, 3)
            indices = np.round((coords - ipp) / spacing).astype(int)
            for idx in indices:
                z, y, x = idx[::-1]
                if 0 <= z < dose_shape[0] and 0 <= y < dose_shape[1] and 0 <= x < dose_shape[2]:
                    voxels.append(dose_grid[z, y, x])
        if voxels:
            mean_doses[roi_num] = float(np.mean(voxels))

    return mean_doses


# ══════════════════════════════════════════════════════════════════════════════
# Step 1 — Build uid_to_files index
# ══════════════════════════════════════════════════════════════════════════════

file_RS = trova_file_con_prefisso(DATASET_PATH, 'RS') + trova_file_con_prefisso(DATASET_PATH, 'RTS')
file_RP = trova_file_con_prefisso(DATASET_PATH, 'RP') + trova_file_con_prefisso(DATASET_PATH, 'RTP')
file_RD = trova_file_con_prefisso(DATASET_PATH, 'RD') + trova_file_con_prefisso(DATASET_PATH, 'RTD')

print(f"Found {len(file_RS)} RS | {len(file_RP)} RP | {len(file_RD)} RD files")

# FIX: previously RP/RD were indexed by position (file_RP[i]), which silently
# mismatches when the three lists differ in length or order. Now we build the
# index from the RS files only and note when counterparts are missing.
uid_to_files: dict = {}
study_UIDS:   list = []

for rs_path in file_RS:
    parts = rs_path.split('/')
    uid = parts[-2] if parts[-2] == parts[-3] else f"{parts[-3]}_{parts[-2]}"

    # Find matching RP / RD by sharing the same parent folder
    parent = os.path.dirname(rs_path)
    rp_match = next((f for f in file_RP if os.path.dirname(f) == parent), None)
    rd_match = next((f for f in file_RD if os.path.dirname(f) == parent), None)

    uid_to_files[uid] = {"RS": rs_path, "RP": rp_match, "RD": rd_match}
    study_UIDS.append(uid)

    if rp_match is None: print(f"⚠️  No RP found for {uid}")
    if rd_match is None: print(f"⚠️  No RD found for {uid}")


# ══════════════════════════════════════════════════════════════════════════════
# Step 2 — Read prescriptions and identify target ROIs
# ══════════════════════════════════════════════════════════════════════════════

study_to_target: dict = {}

for studyUID in study_UIDS.copy():
    study_to_target[studyUID] = {
        "Prescription": None, "Number": None, "Name": None, "Plan": None
    }
    try:
        rp = pydicom.dcmread(ottieni_file_da_uid(uid_to_files, studyUID, 'RP'))
        study_to_target[studyUID]["Prescription"] = float(
            rp.DoseReferenceSequence[0].TargetPrescriptionDose
        )
        study_to_target[studyUID]["Plan"] = rp.RTPlanLabel
    except Exception as e:
        print(f"⚠️  Could not read prescription for {studyUID}: {e}")
        val = input("Enter prescription dose in Gy (or 'NA' to skip): ").strip()
        if val.upper() == 'NA':
            del study_to_target[studyUID]
            study_UIDS.remove(studyUID)
            continue
        study_to_target[studyUID]["Prescription"] = float(val)

# Identify target ROI numbers
for studyUID in study_UIDS.copy():
    prs = float(study_to_target[studyUID]["Prescription"])
    targets = []

    try:
        rd = pydicom.dcmread(ottieni_file_da_uid(uid_to_files, studyUID, 'RD'))
        if hasattr(rd, 'DVHSequence'):
            targets = [
                dvh.DVHReferencedROISequence[0].ReferencedROINumber
                for dvh in rd.DVHSequence
                if float(dvh.DVHMeanDose) >= 0.5 * prs
            ]
    except Exception:
        pass

    if not targets:
        print(f"  DVH unavailable or empty for {studyUID} — using dose-based fallback")
        try:
            targets = calcola_target_da_dose(uid_to_files, studyUID, prs)
        except Exception as e:
            print(f"  ❌ Dose-based fallback failed for {studyUID}: {e}")

    study_to_target[studyUID]["Number"] = targets if targets else 'nf'

# Resolve ROI numbers → names
for studyUID in study_UIDS.copy():
    try:
        rs = pydicom.dcmread(ottieni_file_da_uid(uid_to_files, studyUID, 'RS'))
        target_nums = study_to_target[studyUID]["Number"]
        if target_nums == 'nf':
            continue
        names = [
            roi.ROIName
            for roi in rs.StructureSetROISequence
            if roi.ROINumber in target_nums
        ]
        if names:
            study_to_target[studyUID]["Name"] = names
        else:
            print(f"No target names found for {studyUID} — removing")
            del study_to_target[studyUID]
            study_UIDS.remove(studyUID)
    except Exception as e:
        print(f"Error reading RS for {studyUID}: {e} — removing")
        del study_to_target[studyUID]
        study_UIDS.remove(studyUID)

# Remove entries with no Number and no Name
study_to_target = {
    k: v for k, v in study_to_target.items()
    if not (v["Number"] is None and v["Name"] is None)
}


# ══════════════════════════════════════════════════════════════════════════════
# Step 3 — Filter to CTV/ITV/PTV only; pair them up
# ══════════════════════════════════════════════════════════════════════════════

KEYWORDS = {'CTV', 'PTV', 'ITV'}

# Exact upper-cased names to exclude even if they contain a keyword.
# Add any other names you want globally ignored here.
EXCLUDED_NAMES = {'CTV_IN'}

# Keep only ROIs whose name contains a known keyword AND is not excluded.
# The exclusion check uses startswith so "CTV_in", "CTV_IN", "CTV_in_something"
# are all caught regardless of capitalisation or trailing characters.
filtered = {}
for key, value in study_to_target.items():
    pairs = [
        (n, num) for n, num in zip(value["Name"], value["Number"])
        if any(k in n.upper() for k in KEYWORDS)
        and not any(n.upper() == ex or n.upper().startswith(ex + '_') for ex in EXCLUDED_NAMES)
    ]
    if pairs:
        names, numbers = zip(*pairs)
        filtered[key] = {**value, "Name": list(names), "Number": list(numbers)}

# If ITV is present, drop CTV (ITV supersedes CTV)
for key, value in filtered.items():
    names, numbers = value["Name"], value["Number"]
    if any("ITV" in n.upper() for n in names):
        pairs = [(n, num) for n, num in zip(names, numbers) if "CTV" not in n.upper()]
        if pairs:
            names, numbers = zip(*pairs)
            filtered[key]["Name"]   = list(names)
            filtered[key]["Number"] = list(numbers)

display(pd.DataFrame.from_dict(filtered, orient="index"))

# Separate ITV/CTV from PTV and check counts match
final_clean_data:    dict = {}
mismatched_data:     dict = {}

for key, value in filtered.items():
    names, numbers = value["Name"], value["Number"]
    itv_ctv = [(n, num) for n, num in zip(names, numbers) if "CTV" in n.upper() or "ITV" in n.upper()]
    ptv     = [(n, num) for n, num in zip(names, numbers) if "PTV" in n.upper()]

    base = {"Prescription": value["Prescription"], "Plan": value["Plan"],
            "ITV/CTV": [x[0] for x in itv_ctv], "ITV/CTV_Number": [x[1] for x in itv_ctv],
            "PTV":     [x[0] for x in ptv],      "PTV_Number":     [x[1] for x in ptv]}

    if len(itv_ctv) == len(ptv):
        final_clean_data[key] = base
    else:
        mismatched_data[key] = base

# Auto-resolve mismatches: pick the top-N highest-dose PTVs
fixed_mismatched: dict = {}

for studyUID, value in mismatched_data.items():
    itv_ctv_list    = value["ITV/CTV"]
    itv_ctv_numbers = value["ITV/CTV_Number"]
    ptv_list        = value["PTV"]
    ptv_numbers     = value["PTV_Number"]
    n_needed        = len(itv_ctv_list)

    ptv_doses = get_mean_dose_per_roi(uid_to_files, studyUID,
                                      roi_numbers=[str(n) for n in ptv_numbers])

    if ptv_doses:
        top_ptv = sorted(ptv_doses, key=ptv_doses.get, reverse=True)[:n_needed]
        sel_names = [n for n, num in zip(ptv_list, ptv_numbers) if str(num) in top_ptv]
    else:
        print(f"No dose data for PTVs in {studyUID} — manual selection required")
        sel_names = []
        top_ptv   = []

    if len(itv_ctv_list) == len(sel_names):
        fixed_mismatched[studyUID] = {
            **value,
            "PTV": sel_names,
            "PTV_Number": top_ptv,
        }
    else:
        # Manual fallback
        print(f"\n⚠️  MISMATCH in {studyUID}")
        print(f"  ITV/CTV:  {itv_ctv_list}  {itv_ctv_numbers}")
        print(f"  PTV:      {ptv_list}  {ptv_numbers}")

        itv_ctv_list    = input("Select ITV/CTV names (comma-separated): ").split(',')
        itv_ctv_numbers = input("Select ITV/CTV numbers (comma-separated): ").split(',')
        sel_names       = input("Select PTV names (comma-separated): ").split(',')
        top_ptv         = input("Select PTV numbers (comma-separated): ").split(',')

        fixed_mismatched[studyUID] = {
            "Prescription": value["Prescription"], "Plan": value["Plan"],
            "ITV/CTV": itv_ctv_list, "ITV/CTV_Number": itv_ctv_numbers,
            "PTV": sel_names, "PTV_Number": top_ptv,
        }

final_clean_data.update(fixed_mismatched)
df1 = pd.DataFrame.from_dict(final_clean_data, orient="index")
display(df1)


# ══════════════════════════════════════════════════════════════════════════════
# Step 4 — Crop detection per study
# ══════════════════════════════════════════════════════════════════════════════

def _crop_record() -> dict:
    return {
        "Plan": None, "Prescription": None,
        "ITV/CTV": None, "ITV/CTV ID": None,
        "PTV": None, "PTV ID": None,
        "Expansion (mm)": None, "Crop": None,
        "Max crop distance (mm)": None, "Cropped voxels (%)": None,
    }


def _analyse_pair(study_key: str, row: pd.Series, contour,
                  ctv_name: str, ctv_num, ptv_name: str, ptv_num,
                  study_to_crop: dict) -> None:
    """Compute expansion / crop stats for one CTV–PTV pair and write to study_to_crop."""
    rec = _crop_record()
    rec["Plan"]         = row["Plan"]
    rec["Prescription"] = row["Prescription"]
    rec["ITV/CTV"]      = ctv_name
    rec["ITV/CTV ID"]   = ctv_num
    rec["PTV"]          = ptv_name
    rec["PTV ID"]       = ptv_num

    print(f"  CTV/ITV: {ctv_name} (#{ctv_num})  |  PTV: {ptv_name} (#{ptv_num})")

    pti_ctv = extract_contour_points(contour, ctv_num)
    pti_ptv = extract_contour_points(contour, ptv_num)

    if not pti_ctv or not pti_ptv:
        print(f"  ⚠️  Empty contour data for {study_key} — skipping")
        study_to_crop[study_key] = rec
        return

    S1 = np.array(pti_ctv).reshape(-1, 3)
    S2 = np.array(pti_ptv).reshape(-1, 3)

    exp, cropped, max_crop = process_struct(S1, S2)

    rec["Expansion (mm)"] = round(exp)
    crop_frac = len(cropped) / len(S2) if len(S2) > 0 else 0

    if crop_frac > CROP_THRESHOLD:
        print(f"  🔶 Likely cropped — {round(crop_frac * 100)}% of PTV points cropped\n")
        rec["Crop"] = 'Yes'
        rec["Max crop distance (mm)"]  = round(max_crop)
        rec["Cropped voxels (%)"]      = round(crop_frac * 100)
    else:
        print(f"  ✔  Not cropped\n")
        rec["Crop"] = 'No'
        rec["Max crop distance (mm)"]  = '-'
        rec["Cropped voxels (%)"]      = '-'

    study_to_crop[study_key] = rec


study_to_crop: dict = {}

for j in study_UIDS:
    print(f"\n── Study {j}")
    try:
        rs_path = ottieni_file_da_uid(uid_to_files, j, 'RS')
        contour = pydicom.dcmread(rs_path).ROIContourSequence
        row     = df1.loc[j]

        ctv_list  = row["ITV/CTV"]
        ctv_nums  = row["ITV/CTV_Number"]
        ptv_list  = row["PTV"]
        ptv_nums  = row["PTV_Number"]

        if len(ctv_list) > 1:
            # Multiple targets — show both lists with names AND numbers so the
            # user can see which structures to pair, then reorder PTVs to match.
            print(f"\n  Multiple ITV/CTV ({len(ctv_list)}) found — please pair each PTV to its CTV.\n")
            print(f"  ITV/CTV list (fixed order):")
            for i, (cn, cnum) in enumerate(zip(ctv_list, ctv_nums)):
                print(f"    [{i}]  {cn}  (ROI #{cnum})")
            print(f"\n  PTV list (you will reorder this to match the CTV order above):")
            for i, (pn, pnum) in enumerate(zip(ptv_list, ptv_nums)):
                print(f"    [{i}]  {pn}  (ROI #{pnum})")
            print()
            # riordina_liste will ask: "new position for PTV_X?"
            # answer with the index of the CTV it belongs to.
            ptv_list, ptv_nums = riordina_liste(ptv_list, ptv_nums)

            for t in range(len(ctv_list)):
                key = f"{j}_n{t+1}"
                _analyse_pair(key, row, contour,
                              ctv_list[t], ctv_nums[t],
                              ptv_list[t], ptv_nums[t],
                              study_to_crop)
        else:
            _analyse_pair(j, row, contour,
                          ctv_list[0], ctv_nums[0],
                          ptv_list[0], ptv_nums[0],
                          study_to_crop)

    except Exception as e:
        print(f"  ❌ Error in {j}: {e}")


# ══════════════════════════════════════════════════════════════════════════════
# Step 5 — Export
# ══════════════════════════════════════════════════════════════════════════════

df2 = pd.DataFrame.from_dict(study_to_crop, orient="index")
display(df2)
df2.to_excel(MAINFOLDER + 'crop_analysis_new.xlsx')

df3 = pd.DataFrame.from_dict(uid_to_files, orient="index")
df3.to_excel(MAINFOLDER + 'uid_to_files_new.xlsx')

print("\n✅  Saved crop_analysis_new.xlsx and uid_to_files_new.xlsx")

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df1)

