# -*- coding: utf-8 -*-
"""2_PTV_reconst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12dGYvbM81052HN1rCRhc5vi34lUNbF8P
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -r /content/drive/MyDrive/req.txt

# -*- coding: utf-8 -*-
"""
2_ptv_reconstruct.py  —  Rebuild cropped PTVs via 3-D margin expansion.

For every study flagged as Crop=Yes in crop_analysis.xlsx:
  1. Copy the DICOM folder to rebuilt/<study_id>/
  2. Load the RTStruct with rt_utils
  3. Expand the CTV mask by the expected margin (real-mm, 3-D signed distance)
  4. Add the expanded mask as a new ROI  (<PTV>_rebuilt)
  5. Save RS.rebuilt.dcm
"""

# ── Standard imports ──────────────────────────────────────────────────────────
import os
import shutil

import numpy as np
import pandas as pd
import pydicom
from glob import glob
from scipy.ndimage import distance_transform_edt
from rt_utils import RTStructBuilder
from skimage import measure
from shapely.geometry import Polygon, MultiPoint
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

# ── Configuration ─────────────────────────────────────────────────────────────
MAINFOLDER = '/content/drive/MyDrive/ColabNotebooks/crop/'


# ══════════════════════════════════════════════════════════════════════════════
# Core functions
# ══════════════════════════════════════════════════════════════════════════════

def expand_structure_3d(rtstruct, roi_name: str,
                        expansion_mm: float,
                        voxel_spacing: list[float]) -> np.ndarray:
    """
    Expand an RTStruct ROI by *expansion_mm* in real millimetres (3-D).

    Uses a signed-distance-field approach so the expansion is isotropic in
    physical space regardless of anisotropic voxel spacing.

    Parameters
    ----------
    rtstruct       : rt_utils RTStruct object
    roi_name       : name of the source ROI (CTV / ITV)
    expansion_mm   : margin to add in mm
    voxel_spacing  : [row_mm, col_mm, slice_mm]  (x, y, z)

    Returns
    -------
    expanded_mask : bool ndarray with the same shape as the CT volume
    """
    mask = rtstruct.get_roi_mask_by_name(roi_name)

    # Distance from every *outside* voxel to the ROI surface
    dist_outside = distance_transform_edt(~mask, sampling=voxel_spacing)
    # Distance from every *inside* voxel to the ROI surface
    dist_inside  = distance_transform_edt( mask, sampling=voxel_spacing)

    # Signed distance: positive inside, negative outside
    signed_dist = dist_inside - dist_outside

    # Include voxels within expansion_mm of the surface (on the outside)
    return signed_dist >= -expansion_mm


def compute_voxel_spacing(ct_files: list[str]) -> list[float]:
    """
    Derive (x, y, z) voxel spacing from the CT series.

    BUGFIX (root cause of insufficient cranio-caudal expansion): z spacing
    used to be computed from ct_files[0] and ct_files[1] straight out of the
    caller's `sorted(os.listdir(...))` call. That sort is ALPHABETICAL ON
    FILENAME — and CT filenames are DICOM SOPInstanceUIDs, which have no
    relationship to slice position in space. So the "first two" files were
    essentially two RANDOM slices, not physically adjacent ones, and the
    z_spacing derived from their ImagePositionPatient difference could be
    off by an order of magnitude (e.g. 66 mm estimated instead of a true
    3 mm slice spacing). Since expand_structure_3d() uses this value as the
    physical sampling for the 3-D distance transform, an inflated z_spacing
    makes each z-step "worth" far more physical mm than it really is, so
    the isotropic mm margin gets satisfied after far fewer slices — the
    expansion silently stops short in the cranio-caudal direction while
    still being correct in-plane (X/Y), exactly the pattern of the rebuilt
    PTV closely hugging the CTV on sagittal/coronal views.

    Fix: sort ALL slices by their actual ImagePositionPatient Z coordinate
    (not filename), then take the MEDIAN of consecutive z-gaps — robust to
    a missing/duplicated slice here or there, unlike using just two files.
    """
    datasets = [pydicom.dcmread(f, stop_before_pixels=True) for f in ct_files]
    datasets.sort(key=lambda ds: float(ds.ImagePositionPatient[2]))

    first = datasets[0]
    xy = [float(x) for x in first.PixelSpacing]

    if len(datasets) >= 2:
        z_positions = [float(ds.ImagePositionPatient[2]) for ds in datasets]
        z_diffs = np.abs(np.diff(z_positions))
        z_spacing = float(np.median(z_diffs))
        if z_spacing == 0 or np.any(z_diffs > 3 * z_spacing):
            print(f"  ⚠️  Irregular slice spacing detected (gaps: "
                  f"{np.round(np.unique(z_diffs), 2)} mm) — check for duplicate/missing slices")
    else:
        z_spacing = float(first.SliceThickness)

    return xy + [z_spacing]


def plot_3d_mask(mask: np.ndarray, color: str = 'red', alpha: float = 0.5):
    """Return a Poly3DCollection mesh for the given boolean mask (for QA plots)."""
    verts, faces, _, _ = measure.marching_cubes(mask, level=0.5)
    mesh = Poly3DCollection(verts[faces], alpha=alpha)
    mesh.set_facecolor(color)
    return mesh


def _fix_roi_numbers(rtstruct, roi_name: str) -> bool:
    """
    After rt_utils adds a new ROI it may assign a ROINumber that is a
    DUPLICATE of an already-existing ROI (e.g. it reuses the CTV's number).
    This function gives the new ROI a truly unique number and re-links
    every DICOM sequence that references it by ROI number.

    BUGFIX (root cause of "3_coverage_scores doesn't see the new expanded
    contour"): rt_utils always *appends* the new ROI's entries at the END
    of StructureSetROISequence / ROIContourSequence / RTROIObservationsSequence.
    When the assigned number collides with an existing ROI, there are TWO
    entries in ROIContourSequence sharing that duplicate number: the
    pre-existing one (earlier in the sequence) and the brand-new expanded
    contour (the one just appended, i.e. LAST). The previous version of
    this function scanned the sequence FORWARDS and re-linked the FIRST
    match — which is the *pre-existing* ROI, not the new one. The result:
    the new "<PTV>_rebuilt" ROI ended up pointing at someone else's old
    contour (e.g. the CTV's), while the actual expanded-mask contour data
    was left orphaned under the stale duplicate number. Coverage scoring
    downstream then silently read the wrong (unexpanded) geometry instead
    of raising an error.

    Fix: scan each sequence in REVERSE so the LAST (i.e. newly appended)
    matching entry is the one re-linked, leaving the pre-existing ROI's
    entry untouched.

    Returns True on success, False if the ROI was not found.
    """
    # Find old (possibly duplicate) number assigned by rt_utils
    old_number = None
    for roi in rtstruct.ds.StructureSetROISequence:
        if roi.ROIName == roi_name:
            old_number = roi.ROINumber
            break

    if old_number is None:
        return False

    # Assign a truly unique number
    used = {roi.ROINumber for roi in rtstruct.ds.StructureSetROISequence
            if roi.ROIName != roi_name}
    new_number = 1
    while new_number in used:
        new_number += 1

    if new_number == old_number:
        return True  # already unique, nothing to do

    # Update StructureSetROISequence (the new ROI's own entry — unique by name)
    for roi in rtstruct.ds.StructureSetROISequence:
        if roi.ROIName == roi_name:
            roi.ROINumber = new_number
            break

    # Update ROIContourSequence — the new ROI's contour was appended LAST,
    # so scan in reverse to grab it instead of an earlier, pre-existing
    # ROI that happens to share the same (duplicate) number.
    updated_contour = False
    for roi_contour in reversed(rtstruct.ds.ROIContourSequence):
        if roi_contour.ReferencedROINumber == old_number and not updated_contour:
            roi_contour.ReferencedROINumber = new_number
            updated_contour = True

    if not updated_contour:
        print(f"  ⚠️  No ROIContour entry found for ROI number {old_number}")

    # Update RTROIObservationsSequence too, for DICOM consistency (some
    # viewers / downstream tools key off this sequence as well). Same
    # duplicate-number issue, same reverse-scan fix.
    updated_obs = False
    if hasattr(rtstruct.ds, 'RTROIObservationsSequence'):
        for obs in reversed(rtstruct.ds.RTROIObservationsSequence):
            if obs.ReferencedROINumber == old_number and not updated_obs:
                obs.ReferencedROINumber = new_number
                updated_obs = True

    return updated_contour


# ══════════════════════════════════════════════════════════════════════════════
# Main loop
# ══════════════════════════════════════════════════════════════════════════════

df_uidtofiles = pd.read_excel(MAINFOLDER + 'uid_to_files_new.xlsx',    index_col=0, engine='openpyxl')
df_crop       = pd.read_excel(MAINFOLDER + 'crop_analysis_new.xlsx',   index_col=0, engine='openpyxl')

display(df_uidtofiles)
display(df_crop)

for index, row in df_crop.iterrows():
    # Normalise index: strip trailing "_n?" suffix to get the base UID key
    base_uid = index[:-3] if index[-3:-1] == '_n' else index

    if row['Crop'] != 'Yes':
        continue

    print(f"\n── {index}")
    try:
        fileRS    = df_uidtofiles.loc[base_uid, 'RS']
        rs_folder = os.path.dirname(fileRS)
        dest_folder = os.path.join(MAINFOLDER, 'rebuilt', str(index))

        # ── Build sorted CT file list (reads from original, no copy) ───────
        ct_files = sorted([
            os.path.join(rs_folder, f)
            for f in os.listdir(rs_folder)
            if f.startswith('CT.') and f.endswith('.dcm')
        ])
        if not ct_files:
            print(f"  ⚠️  No CT files found for {index} — skipping")
            continue

        # ── Copy only plan files to dest_folder — no CTs ─────────────────
        # Copying the full CT series (often 100s of files) doubles disk usage.
        # We only need RP, RD, and the new rebuilt RS in the output folder.
        os.makedirs(dest_folder, exist_ok=True)
        plan_prefixes = ('RP', 'RTP', 'RD', 'RTD', 'RS', 'RTS')
        for f in os.listdir(rs_folder):
            if any(f.startswith(p) for p in plan_prefixes):
                shutil.copy(os.path.join(rs_folder, f), dest_folder)

        # Remove the original RS — will be replaced by RS.rebuilt.dcm
        old_rs_files = (
            glob(os.path.join(dest_folder, 'RS*.dcm')) +
            glob(os.path.join(dest_folder, 'RTS*.dcm'))
        )
        if not old_rs_files:
            print(f"  ⚠️  No RS/RTS file to remove in {dest_folder} — skipping")
            continue
        os.remove(old_rs_files[0])

        # ── RTStructBuilder needs a folder with ONLY CT files ─────────────
        # Google Drive does not support symlinks, so we copy the CTs here.
        # dest_folder contains only plan files (RP, RD, rebuilt RS), so
        # this is still just one copy of the CTs total — not two.
        ct_only_folder = os.path.join(dest_folder, 'ct_only')
        os.makedirs(ct_only_folder, exist_ok=True)
        for ct_path in ct_files:
            dest_ct = os.path.join(ct_only_folder, os.path.basename(ct_path))
            if not os.path.exists(dest_ct):
                shutil.copy(ct_path, dest_ct)

        # ── Load RTStruct ──────────────────────────────────────────────────
        rtstruct = RTStructBuilder.create_from(
            dicom_series_path=ct_only_folder,
            rt_struct_path=fileRS,
        )

        ctv_name      = row['ITV/CTV']
        expansion_mm  = float(row['Expansion (mm)'])
        new_roi_name  = row['PTV'] + '_rebuilt'  # defined early so it's available in error messages

        # ── Voxel spacing (uses ImagePositionPatient for z, more reliable) ─
        voxel_spacing = compute_voxel_spacing(ct_files)
        print(f"  ℹ️  voxel spacing (row, col, z) mm: "
              f"[{voxel_spacing[0]:.3f}, {voxel_spacing[1]:.3f}, {voxel_spacing[2]:.3f}]")

        # ── 3-D expansion ──────────────────────────────────────────────────
        expanded_mask = expand_structure_3d(rtstruct, ctv_name, expansion_mm, voxel_spacing)

        if not np.any(expanded_mask):
            print(f"  ❌ Expanded mask for {new_roi_name} is empty — skipping")
            continue

        # ── Add new ROI ────────────────────────────────────────────────────
        rtstruct.add_roi(mask=expanded_mask, color=[255, 0, 0], name=new_roi_name)

        # ── Fix potentially duplicate ROI number assigned by rt_utils ──────
        if not _fix_roi_numbers(rtstruct, new_roi_name):
            print(f"  ❌ Could not find {new_roi_name} in StructureSetROISequence — skipping")
            continue

        # ── Save ───────────────────────────────────────────────────────────
        output_file = os.path.join(dest_folder, 'RS.rebuilt.dcm')
        rtstruct.save(output_file)

        # ── Sanity check ──────────────────────────────────────────────────
        # Re-read the file just written and make sure the new ROI is really
        # linked to its own (expanded) contour, not to another structure's.
        # This is what would have caught the ROI-numbering bug earlier:
        # previously the "_rebuilt" ROI could silently end up pointing at
        # the CTV's original (unexpanded) contour.
        check_ds = pydicom.dcmread(output_file)
        new_roi_number = next(
            (r.ROINumber for r in check_ds.StructureSetROISequence
             if r.ROIName == new_roi_name), None
        )
        new_contour_seq = next(
            (rc.ContourSequence for rc in check_ds.ROIContourSequence
             if rc.ReferencedROINumber == new_roi_number and hasattr(rc, 'ContourSequence')),
            None
        )
        ctv_roi_number = next(
            (r.ROINumber for r in check_ds.StructureSetROISequence
             if r.ROIName == ctv_name), None
        )
        ctv_contour_seq = next(
            (rc.ContourSequence for rc in check_ds.ROIContourSequence
             if rc.ReferencedROINumber == ctv_roi_number and hasattr(rc, 'ContourSequence')),
            None
        )
        if new_contour_seq is None:
            print(f"  ❌ Sanity check FAILED: {new_roi_name} has no linked contour in the saved file!")
        elif ctv_contour_seq is not None and new_contour_seq is ctv_contour_seq:
            print(f"  ❌ Sanity check FAILED: {new_roi_name} is linked to the SAME contour object as {ctv_name}!")
        else:
            n_new_points = sum(len(c.ContourData) for c in new_contour_seq)
            n_ctv_points = sum(len(c.ContourData) for c in ctv_contour_seq) if ctv_contour_seq else 0
            print(f"  ✔ Saved {new_roi_name}  →  {output_file}"
                  f"  (contour points: {n_new_points}, CTV: {n_ctv_points})")

    except Exception as e:
        print(f"  ❌ Error processing {index}: {e}")
        continue