# -*- coding: utf-8 -*-
"""3_Coverage_scores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pp7bvSYD8jkZFO30SVesclApngnfyGNB
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -r /content/drive/MyDrive/req.txt

"""
3_coverage_scores.py  —  Compute DVH metrics (V95, V90, D95, D90, D99, CCI)
                          for CTV, original PTV, and rebuilt PTV.

Reads   : crop_analysis.xlsx, uid_to_files.xlsx, rebuilt2D/<index>/
Outputs : coverage.xlsx
"""

# ── Standard imports ──────────────────────────────────────────────────────────
import os

import numpy as np
import pandas as pd
import pydicom
from glob import glob
from matplotlib.path import Path

# ── Configuration ─────────────────────────────────────────────────────────────
MAINFOLDER = '/content/drive/MyDrive/ColabNotebooks/crop/'
BIN_SIZE   = 0.1   # Gy — DVH bin width


# ══════════════════════════════════════════════════════════════════════════════
# DICOM loaders
# ══════════════════════════════════════════════════════════════════════════════

def trova_file_con_prefisso(cartella_base: str, prefisso: str) -> list[str]:
    """Recursively find all files whose name starts with *prefisso*."""
    return [
        os.path.join(root, f)
        for root, _, files in os.walk(cartella_base)
        for f in files
        if f.startswith(prefisso)
    ]


def load_dose(dose_path: str) -> tuple[np.ndarray, list, list, object]:
    """
    Load an RTDOSE file.

    Returns
    -------
    dose    : 3-D float array in Gy  (shape: slices × rows × cols)
    spacing : [x_mm, y_mm, z_mm]
    origin  : [x0, y0, z0] in mm (ImagePositionPatient)
    ds      : raw pydicom Dataset (for any extra attributes)
    """
    ds = pydicom.dcmread(dose_path)
    dose = ds.pixel_array.astype(float) * float(ds.DoseGridScaling)
    spacing = [
        float(ds.PixelSpacing[0]),
        float(ds.PixelSpacing[1]),
        float(ds.GridFrameOffsetVector[1]) - float(ds.GridFrameOffsetVector[0]),
    ]
    origin = [float(v) for v in ds.ImagePositionPatient]
    return dose, spacing, origin, ds


def extract_structure_mask(rtstruct_path: str,
                           dose_shape: tuple,
                           dose_spacing: list,
                           dose_origin: list,
                           structure_name: str) -> np.ndarray:
    """
    Rasterise an RT structure onto the dose grid.

    Returns a bool ndarray of shape *dose_shape* (slices × rows × cols).
    Raises ValueError if the structure is not found or has no contours.
    """
    ds = pydicom.dcmread(rtstruct_path)

    # Look up ROI number
    roi_number = next(
        (roi.ROINumber for roi in ds.StructureSetROISequence
         if roi.ROIName == structure_name),
        None,
    )
    if roi_number is None:
        raise ValueError(f"Structure '{structure_name}' not found in {rtstruct_path}.")

    # Get contour sequence
    contour_seq = next(
        (roi.ContourSequence for roi in ds.ROIContourSequence
         if roi.ReferencedROINumber == roi_number and hasattr(roi, 'ContourSequence')),
        None,
    )
    if contour_seq is None:
        raise ValueError(f"No contours for '{structure_name}'.")

    mask = np.zeros(dose_shape, dtype=bool)

    for contour in contour_seq:
        points  = np.array(contour.ContourData).reshape(-1, 3)
        z       = points[0, 2]
        z_index = int(round((z - dose_origin[2]) / dose_spacing[2]))

        if not (0 <= z_index < dose_shape[0]):
            continue

        # Patient → pixel coordinates (floating point for polygon path)
        x_px = (points[:, 0] - dose_origin[0]) / dose_spacing[0]
        y_px = (points[:, 1] - dose_origin[1]) / dose_spacing[1]

        poly_path = Path(np.column_stack((x_px, y_px)))

        # Build a grid of pixel centres and test containment
        xi, yi = np.meshgrid(np.arange(dose_shape[2]), np.arange(dose_shape[1]))
        coords  = np.column_stack((xi.ravel(), yi.ravel()))
        inside  = poly_path.contains_points(coords).reshape(dose_shape[1], dose_shape[2])

        mask[z_index] |= inside

    return mask


# ══════════════════════════════════════════════════════════════════════════════
# DVH metrics
# ══════════════════════════════════════════════════════════════════════════════

def compute_dvh_metrics(dose: np.ndarray, mask: np.ndarray,
                        prescribed_dose: float,
                        bin_size: float = BIN_SIZE) -> dict:
    """
    Compute DVH-based coverage metrics for a single structure.

    Returns a dict with keys:
        dvh_x, dvh_y  — cumulative DVH curve (for plotting)
        V95, V90      — volume fraction (%) receiving ≥ 95%/90% of prescription
        D95, D90, D99 — dose (Gy) at 95th/90th/99th percentile of coverage
        CCI           — conformity index  D99 / prescription
    """
    dose_vals = dose[mask].astype(float)
    if dose_vals.size == 0:
        nan = float('nan')
        return dict(dvh_x=np.array([]), dvh_y=np.array([]),
                    V95=nan, V90=nan, D95=nan, D90=nan, D99=nan, CCI=nan)

    # Cumulative DVH
    bins      = np.arange(0, dose_vals.max() + bin_size, bin_size)
    hist, edges = np.histogram(dose_vals, bins=bins)
    cumulative  = np.cumsum(hist[::-1])[::-1]
    dvh_y       = cumulative / cumulative[0] * 100
    dvh_x       = edges[:-1]

    n = dose_vals.size

    def _vx(threshold_gy: float) -> float:
        return float(np.sum(dose_vals >= threshold_gy) / n * 100)

    def _dx(percent: float) -> float:
        """Dose received by the highest-dose *percent* % of the volume."""
        sorted_desc = np.sort(dose_vals)[::-1]
        idx = min(int(np.ceil(percent / 100 * n)) - 1, n - 1)
        return float(sorted_desc[max(idx, 0)])

    v95 = _vx(0.95 * prescribed_dose)
    v90 = _vx(0.90 * prescribed_dose)
    d95 = _dx(95)
    d90 = _dx(90)
    d99 = _dx(99)

    return dict(
        dvh_x=dvh_x, dvh_y=dvh_y,
        V95=v95, V90=v90,
        D95=d95, D90=d90, D99=d99,
        CCI=d99 / prescribed_dose if prescribed_dose else float('nan'),
    )


# ══════════════════════════════════════════════════════════════════════════════
# Main loop
# ══════════════════════════════════════════════════════════════════════════════

df_crop  = pd.read_excel(MAINFOLDER + 'crop_analysis_new.xlsx', index_col=0, engine='openpyxl')
df_files = pd.read_excel(MAINFOLDER + 'uid_to_files_new.xlsx',  index_col=0, engine='openpyxl')
display(df_crop)

# Columns we will write (initialised to NaN so unfilled rows stay clean)
METRIC_COLS = [
    'V95 CTV', 'V90 CTV', 'D95 CTV', 'D90 CTV', 'D99 CTV', 'CCI CTV',
    'V95 PTV', 'V90 PTV', 'D95 PTV', 'D90 PTV', 'D99 PTV', 'CCI PTV',
    'V95 hPTV','V90 hPTV','D95 hPTV','D90 hPTV','D99 hPTV','CCI hPTV',
]
for col in METRIC_COLS:
    if col not in df_crop.columns:
        df_crop[col] = float('nan')


def _write_metrics(df: pd.DataFrame, index: str,
                   prefix: str, m: dict) -> None:
    """Write metric dict into the DataFrame row, rounding to 2 dp."""
    for key in ('V95', 'V90', 'D95', 'D90', 'D99', 'CCI'):
        df.loc[index, f'{key} {prefix}'] = round(m[key], 2)


for index, row in df_crop.iterrows():
    target      = row['PTV']
    target_ctv  = row['ITV/CTV']
    prescription = float(row['Prescription'])
    is_crop     = row['Crop']

    rebuilt_folder = os.path.join(MAINFOLDER, 'rebuilt', str(index))

    # ── Resolve RS path ──────────────────────────────────────────────────────
    try:
        if is_crop == 'Yes':
            # Use the rebuilt RS (ends with 'modified.dcm')
            rebuilt_rs_candidates = [
                s for s in trova_file_con_prefisso(rebuilt_folder, 'RS')
                if s.endswith('rebuilt.dcm')
            ]
            if not rebuilt_rs_candidates:
                print(f"⚠️  No rebuilt RS found for {index} — skipping")
                continue
            file_RS = rebuilt_rs_candidates[0]

            # Find the _rebuilt ROI name stored in this file
            structure_name = next(
                (k.ROIName for k in pydicom.dcmread(file_RS).StructureSetROISequence
                 if k.ROIName.endswith('_rebuilt')),
                None,
            )
            if structure_name is None:
                print(f"⚠️  No '_rebuilt' ROI in {file_RS} — skipping")
                continue
        else:
            match = [i for i in df_files.index if i in str(index) or str(index) in i]
            if not match:
                print(f"⚠️  No UID match for {index} in uid_to_files — skipping")
                continue
            file_RS = df_files.loc[match[0], 'RS']
            structure_name = target

        # ── Resolve RD path ──────────────────────────────────────────────────
        match = [i for i in df_files.index if i in str(index) or str(index) in i]
        if not match:
            print(f"⚠️  No UID match for {index} — skipping")
            continue
        file_RD = df_files.loc[match[0], 'RD']

        # ── Load dose ────────────────────────────────────────────────────────
        dose, spacing, origin, _ = load_dose(file_RD)

        # ── Metrics for CTV ──────────────────────────────────────────────────
        mask_ctv = extract_structure_mask(file_RS, dose.shape, spacing, origin, target_ctv)
        m_ctv    = compute_dvh_metrics(dose, mask_ctv, prescription)
        _write_metrics(df_crop, index, 'CTV', m_ctv)

        # ── Metrics for original PTV ─────────────────────────────────────────
        mask_ptv = extract_structure_mask(file_RS, dose.shape, spacing, origin, target)
        m_ptv    = compute_dvh_metrics(dose, mask_ptv, prescription)
        _write_metrics(df_crop, index, 'PTV', m_ptv)

        # ── Metrics for rebuilt PTV (hPTV) ───────────────────────────────────
        mask_hptv = extract_structure_mask(file_RS, dose.shape, spacing, origin, structure_name)
        m_hptv    = compute_dvh_metrics(dose, mask_hptv, prescription)
        _write_metrics(df_crop, index, 'hPTV', m_hptv)

        print(f"✔ {index}")

    except Exception as e:
        print(f"❌ Error in {index}: {e}")

# ── Replace NaN with '-' for display only, keep numeric for saving ────────────
display(df_crop.fillna('-'))

# Drop helper ID columns that were only needed internally
for col in ('ITV/CTV ID', 'PTV ID'):
    if col in df_crop.columns:
        df_crop.drop(columns=col, inplace=True)

df_crop.to_excel(MAINFOLDER + 'coverage.xlsx')
print("\n✅  Saved coverage.xlsx")